<?php

namespace App\Http\Controllers;

use App\Entry;
use Exception as ExceptionAlias;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Illuminate\Http\Request as RequestAlias;

class HomeController extends Controller {

    private $formFields = [
        [
            'field'=> "EstadoPaciente",
            'internalCode'=> 'rating',
            'order'=> 0
        ],
        [
            'field' => "TipoDocumento",
            'internalCode'=> 'cf_935',
            'order'=> 1
        ],
        [
            'field'=> "NumeroDocumento",
            'internalCode'=> 'siccode',
            'order'=> 2
        ],
        [
            'field'=> "PrimerNombre",
            'internalCode'=> 'cf_943',
            'order'=> 3
        ],
        [
            'field'=> "SegundoNombre",
            'internalCode'=> 'cf_937',
            'order'=> 4
        ],
        [
            'field'=> "PrimerApellido",
            'internalCode'=> 'cf_939',
            'order'=> 5
        ],
        [
            'field'=> "SegundoApellido",
            'internalCode'=> 'cf_941',
            'order'=> 6
        ],
        [
            'field'=> "NombresyApellidos",
            'internalCode'=> 'accountname',
            'order'=> 7
        ],
        [
            'field'=> "Iniciales",
            'internalCode'=> 'cf_945',
            'order'=> 8
        ],
        [
            'field'=> "CorreoPaciente",
            'internalCode'=> 'email1',
            'order'=> 9
        ],
        [
            'field'=> "FechaNacimiento",
            'internalCode'=> 'cf_951',
            'order'=> 10
        ],
        [
            'field'=> "EdadActual",
            'internalCode'=> 'cf_953',
            'order'=> 11
        ],
        [
            'field'=>"MenorDeEdad",
            'internalCode'=> 'cf_955',
            'order'=> 12
        ],
        [
            'field'=> "LaboralmenteActivo",
            'internalCode'=> 'cf_1574',
            'order'=> 13
        ],
        [
            'field'=> "Descripcion",
            'internalCode'=> 'description',
            'order'=> 14
        ],
        [
            'field'=> "Genero",
            'internalCode'=> 'cf_957',
            'order'=> 15
        ],
        [
            'field'=> "Pais",
            'internalCode'=> 'cf_2007',
            'order'=> 16
        ],
        [
            'field'=> "Departamento",
            'internalCode'=> 'cf_2009',
            'order'=> 17
        ],
        [
            'field'=> "CiudadResidencia",
            'internalCode'=> 'cf_2011',
            'order'=> 18
        ],
        [
            'field'=> "TipoDezona",
            'internalCode'=> 'cf_1576',
            'order'=> 19
        ],
        [
            'field'=> "Zona",
            'internalCode'=> 'cf_1578',
            'order'=> 20
        ],
        [
            'field'=> "BarrioResidencia",
            'internalCode'=> 'cf_965',
            'order'=> 21
        ],
        [
            'field'=> "Estrato",
            'internalCode'=> 'cf_983',
            'order'=> 22
        ],
        [
            'field'=> "Nomenclatura",
            'internalCode'=> 'cf_985',
            'order'=> 23
        ],
        [
            'field'=> "Nomenclatura1",
            'internalCode'=> 'cf_989',
            'order'=> 24
        ],
        [
            'field'=> "Nomenclatura2",
            'internalCode'=> 'cf_991',
            'order'=> 25
        ],
        [
            'field'=> "DireccionResidencia",
            'internalCode'=> 'bill_street',
            'order'=> 26
        ],
        [
            'field'=> "TipoTelefono1",
            'internalCode'=> 'cf_967',
            'order'=> 27
        ],
        [
            'field'=> "NumeroTelefonico1",
            'internalCode'=> 'phone',
            'order'=> 28
        ],
        [
            'field'=> "TipoTelefono2",
            'internalCode'=> 'cf_1253',
            'order'=> 29
        ],
        [
            'field'=> "NumeroTelefonico2",
            'internalCode'=> 'cf_971',
            'order'=> 30
        ],
        [
            'field'=> "AsignadoA",
            'internalCode'=> 'assigned_user_id',
            'order'=> 31
        ],
        [
            'field'=> "Ocupacion",
            'internalCode'=> 'cf_997',
            'order'=> 32
        ],
        [
            'field'=> "TipoPoblacionAtendida",
            'internalCode'=> 'cf_999',
            'order'=> 33
        ],
        [
            'field'=> "CualPoblacion",
            'internalCode'=> 'cf_1590',
            'order'=> 34
        ],
        [
            'field'=> "TipoDiscapacidad",
            'internalCode'=> 'cf_2013',
            'order'=> 35
        ],
        [
            'field'=> "DiscapacidadFue",
            'internalCode'=> 'cf_1592',
            'order'=> 36
        ],
        [
            'field'=> "GradoDiscapacidad",
            'internalCode'=> 'cf_2015',
            'order'=> 37
        ],
        [
            'field' =>"NivelEducacion",
            'internalCode'=> 'cf_1005',
            'order'=> 38
        ],
        [
            'field'=> "EstadoCivil",
            'internalCode'=> 'cf_947',
            'order'=> 39
        ],
        [
            'field'=> "Regimen",
            'internalCode'=> 'cf_1007',
            'order'=> 40
        ],
        [
            'field'=> "TipoAfiliacion",
            'internalCode'=> 'cf_1011',
            'order'=> 41
        ],
        [
            'field'=> "Eps",
            'internalCode'=> 'cf_1761',
            'order'=> 42
        ],
        [
            'field'=> "IpsAfiliacion",
            'internalCode'=> 'cf_1763',
            'order'=> 43
        ],
        [
            'field'=> "Observaciones",
            'internalCode'=> 'cf_1017',
            'order'=> 44
        ],
        [
            'field'=> "Kam",
            'internalCode'=> 'cf_2019',
            'order'=> 45
        ],
        [
            'field'=> "CiudadAtencion",
            'internalCode'=> 'cf_2017',
            'order'=> 46
        ],
        [
            'field'=> "CargarCedula",
            'internalCode'=> 'cf_1669',
            'order'=> 47
        ],
        [
            'field'=>"CArgarHC",
            'internalCode'=> 'cf_1673',
            'order'=> 48
        ]
    ];
    private $formFieldsHelp = [];

    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function index(Request $request) {
        $currentTime = Carbon::now()->format('Y-m-d');
        $baseUrl = 'https://server3.datacrm.la/datacrm/sanofi/webservice.php';
        $client = new Client(
            [
                'defaults' => [
                    'headers'  => [
                        'content-type' => 'application/x-www-form-urlencoded',
                        'Accept' => 'application/json'
                    ],
                ],
            ]
        );
        $sessionName = $this->getSessionName();
        $cities = ['EL ENCANTO',
            'LA CHORRERA',
            'LA PRADERA',
            'LETICIA',
            'MIRITI',
            'PUERTO NARINO',
            'PUERTO SANTANDER',
            'TARAPACA',
            'ABEJORRAL',
            'ABRIAQUI',
            'ALEJANDRIA',
            'ALTAMIRA',
            'AMAGA',
            'AMALFI',
            'ANDES',
            'ANGELOPOLIS',
            'ANGOSTURA',
            'ANORI',
            'ANTIOQUIA',
            'ANZA',
            'APARTADO',
            'ARBOLETES',
            'ARGELIA',
            'ARMENIA',
            'BARBOSA',
            'BELLO',
            'BELMIRA',
            'BETANIA',
            'BETULIA',
            'BOLIVAR',
            'BRICENO',
            'BURITICA',
            'CACERES',
            'CAICEDO',
            'CALDAS',
            'CAMPAMENTO',
            'CANAS GORDAS',
            'CARACOLI',
            'CARAMANTA',
            'CAREPA',
            'CARMEN DE VIBORAL',
            'CAROLINA',
            'CAUCASIA',
            'CHIGORODO',
            'CISNEROS',
            'COCORNA',
            'CONCEPCION',
            'COPACABANA',
            'DABEIBA',
            'DON MATIAS',
            'EBEJICO',
            'EL BAGRE',
            'ENTRERRIOS',
            'ENVIGADO',
            'FREDONIA',
            'FRONTINO',
            'GIRALDO',
            'GIRARDOTA',
            'GOMEZ PLATA',
            'GRANADA',
            'GUADALUPE',
            'GUARNE',
            'GUATAPE',
            'HELICONIA',
            'HISPANIA',
            'ITAGUI',
            'ITUANGO',
            'JARDIN',
            'JERICO',
            'LA CEJA',
            'LA ESTRELLA',
            'LA UNION',
            'LIBORINA',
            'MACEO',
            'MARINILLA',
            'MEDELLIN',
            'MONTEBELLO',
            'MURINDO',
            'MUTATA',
            'NARINO',
            'NECHI',
            'NECOCLI',
            'OLAYA',
            'PENOL',
            'PEQUE',
            'PUEBLO RICO',
            'PUERTO BERRIO',
            'PUERTO NARE',
            'PUERTO TRIUNFO',
            'REMEDIOS',
            'RETIRO',
            'RIONEGRO',
            'SABANALARGA',
            'SABANETA',
            'SALGAR',
            'SAN ANDRES',
            'SAN CARLOS',
            'SAN CRISTOBAL',
            'SAN FRANCISCO',
            'SAN JERONIMO',
            'SAN JOSE DE MONTANA',
            'SAN JUAN DE URABA',
            'SAN LUIS',
            'SAN PEDRO',
            'SAN PEDRO DE URABA',
            'SAN RAFAEL',
            'SAN ROQUE',
            'SAN VICENTE',
            'SANTA BARBARA',
            'SANTA ROSA DE OSOS',
            'SANTO DOMINGO',
            'SANTUARIO',
            'SEGOVIA',
            'SONSON',
            'SOPETRAN',
            'TAMESIS',
            'TARAZA',
            'TARSO',
            'TITIRIBI',
            'TOLEDO',
            'TURBO',
            'URAMITA',
            'URRAO',
            'VALDIVIA',
            'VALPARAISO',
            'VEGACHI',
            'VENECIA',
            'VIGIA DEL FUERTE',
            'YALI',
            'YARUMAL',
            'YOLOMBO',
            'YONDO',
            'ZARAGOZA',
            'ARAUCA',
            'ARAUQUITA',
            'CRAVO NORTE',
            'FORTUL',
            'SARAVENA',
            'TAME',
            'BARANOA',
            'BARRANQUILLA',
            'CAMPO DE CRUZ',
            'CANDELARIA',
            'GALAPA',
            'LURUACO',
            'MALAMBO',
            'MANATI',
            'PALMAR VARELA',
            'PIOJO',
            'POLONUEVO',
            'PONEDERA',
            'PUERTO COLOMBIA',
            'REPELON',
            'SABANAGRANDE',
            'SABANALARGA',
            'SANTA LUCIA',
            'SANTO TOMAS',
            'SOLEDAD',
            'SUAN',
            'TUBARA',
            'USIACURI',
            'BOGOTA',
            'ACHI',
            'ALT DEL ROSARIO',
            'ARJONA',
            'BARRANCO DE LOBA',
            'CALAMAR',
            'CANTAGALLO',
            'CARMEN DE BOLIVAR',
            'CARTAGENA',
            'CICUCO',
            'CLEMENCIA',
            'CORDOBA',
            'EL GUAMO',
            'EL PENON',
            'HATILLO DE LOBA',
            'MAGANGUE',
            'MAHATES',
            'MARGARITA',
            'MARIA LA BAJA',
            'MOMPOS',
            'MONTECRISTO',
            'MORALES',
            'PINILLOS',
            'REGIDOR',
            'RIO VIEJO',
            'SAN CRISTOBAL',
            'SAN ESTANISLAO',
            'SAN FERNANDO',
            'SAN JACINTO',
            'SAN JUAN NEPOMUCENO',
            'SAN MARTIN DE LOBA',
            'SAN PABLO',
            'SANTA CATALINA',
            'SANTA ROSA',
            'SANTA ROSA SUR',
            'SIMITI',
            'SOPLAVIENTO',
            'TALAIGUA NUEVO',
            'TIQUISIO',
            'TURBACO',
            'TURBANA',
            'VILLANUEVA',
            'ZAMBRANO',
            'ALMEIDA',
            'AQUITANIA',
            'ARCABUCO',
            'BELEN',
            'BELENCITO',
            'BERBEO',
            'BETETIVA',
            'BOAVITA',
            'BOYACA',
            'BRICENO',
            'BUENAVISTA',
            'BUSBANZA',
            'CALDAS',
            'CAMPOHERMOSO',
            'CERINZA',
            'CHINAVITA',
            'CHIQUINQUIRA',
            'CHIQUIZA',
            'CHISCAS',
            'CHITA',
            'CHITARAQUE',
            'CHIVATA',
            'CHIVOR',
            'CIENAGA',
            'COMBITA',
            'COPER',
            'CORRALES',
            'COVARACHIA',
            'CUBARA',
            'CUCAITA',
            'CUITIVA',
            'DUITAMA',
            'EL COCUY',
            'EL ESPINO',
            'FIRAVITOBA',
            'FLORESTA',
            'GACHANTIVA',
            'GAMEZA',
            'GARAGOA',
            'GUACAMAYAS',
            'GUATEQUE',
            'GUAYATA',
            'GUICAN',
            'IZA',
            'JENESANO',
            'JERICO',
            'LA CAPILLA',
            'LA UVITA',
            'LA VICTORIA',
            'LABRANZAGRANDE',
            'MACANAL',
            'MARIPI',
            'MIRAFLORES',
            'MONGUA',
            'MONGUI',
            'MONIQUIRA',
            'MOTAVITA',
            'MUZO',
            'NOBSA',
            'NUEVO COLON',
            'OICATA',
            'OTANCHE',
            'PACHAVITA',
            'PAEZ',
            'PAIPA',
            'PAJARITO',
            'PANQUEBA',
            'PAUNA',
            'PAYA',
            'PAZ DEL RIO',
            'PESCA',
            'PISBA',
            'PUERTO BOYACA',
            'QUIPAMA',
            'RAMIRIQUI',
            'RAQUIRA',
            'RONDON',
            'SABOYA',
            'SACHICA',
            'SAMACA',
            'SAN EDUARDO',
            'SAN JOSE DE PARE',
            'SAN LUIS DE GACENO',
            'SAN MATEO',
            'SAN MIGUEL DE SEMA',
            'SAN PABLO DE BORBUR',
            'SANTA MARIA',
            'SANTA ROSA DE VITERBO',
            'SANTA SOFIA',
            'SANTANA',
            'SATIVA NORTE',
            'SATIVA SUR',
            'SIACHOQUE',
            'SOATA',
            'SOCHA',
            'SOCOTA',
            'SOGAMOSO',
            'SOMONDOCO',
            'SORA',
            'SORACA',
            'SOTAQUIRA',
            'SUSACON',
            'SUTAMARCHAN',
            'SUTATENZA',
            'TAPAGA',
            'TASCO',
            'TENZA',
            'TIBANA',
            'TIBASOSA',
            'TINJACA',
            'TIPACOQUE',
            'TOCA',
            'TOGUI',
            'TOTA',
            'TUNJA',
            'TUNUNGUA',
            'TURMEQUE',
            'TUTA',
            'TUTASA',
            'UMBITA',
            'VENTAQUEMADA',
            'VILLA DE LEYVA',
            'VIRACACHA',
            'ZETAQUIRA',
            'AGUADAS',
            'ANSERMA',
            'ARANZAZU',
            'ARAUCA',
            'ARBOLEDA',
            'BELALCAZAR',
            'BOLIVIA',
            'CHINCHINA',
            'FILADELFIA',
            'FLORENCIA',
            'LA DORADA',
            'LA MERCED',
            'MANIZALES',
            'MANZANARES',
            'MARMATO',
            'MARQUETALIA',
            'MARULANDA',
            'MONTEBONITO',
            'NEIRA',
            'NORCASIA',
            'PACORA',
            'PALESTINA',
            'PENSILVANIA',
            'RIOSUCIO',
            'RISARALDA',
            'SALAMINA',
            'SAMANA',
            'SAN FELIX',
            'SAN JOSE DE RISARALDA',
            'SUPIA',
            'VICTORIA',
            'VILLA MARIA',
            'VITERBO',
            'ALBANIA',
            'BELEN ANDAQUI',
            'CARTAGENA DEL CHAIRA',
            'CURILLO',
            'EL DONCELLO',
            'EL PAUJIL',
            'FLORENCIA',
            'GUACAMAYAS',
            'LA MONTANITA',
            'MATICURO',
            'MILAN',
            'MORELLA',
            'PUERTO RICO',
            'SAN JOSE FRAGUA',
            'SAN VICENTE CAGUAN',
            'SOLANO',
            'SOLITA',
            'VALPARAISO',
            'AGUAZUL',
            'CHAMEZA',
            'HATOM COROZAL',
            'LA SALINA',
            'MANI',
            'MONTERREY',
            'NUNCHIA',
            'OROCUE',
            'PAZ DE ARIPORO',
            'PORE',
            'RECETOR',
            'SABANALARGA',
            'SACAMA',
            'SAN LUIS PALENQUE',
            'TAMARA',
            'TAURAMENA',
            'TRINIDAD',
            'VILLA NUEVA',
            'YOPAL',
            'ALMAGUER',
            'ARGELIA',
            'BALBOA',
            'BOLIVAR',
            'BUENOS AIRES',
            'CAJIBIO',
            'CALDONO',
            'CALOTO',
            'CORINTO',
            'EL TAMBO',
            'FLORENCIA',
            'GUAPI',
            'INZA',
            'JAMBALO',
            'LA SIERRA',
            'LA VEGA',
            'LOPEZ DE MICAY',
            'MERCADERES',
            'MIRANDA',
            'MORALES',
            'PADILLA',
            'PAEZ',
            'PATIA',
            'PIAMONTE',
            'PIENDAMO',
            'POPAYAN',
            'PUERTO TEJADA',
            'PURACE',
            'ROSAS',
            'SAN SEBASTIAN',
            'SANTA ROSA',
            'SANTANDER',
            'SANTANDER DE QUILICHAO',
            'SIBERIA',
            'SILVIA',
            'SOTARA',
            'SUAREZ',
            'TIMBIO',
            'TIMBIQUI',
            'TORIBIO',
            'TOTORO',
            'AGUACHICA',
            'AGUSTIN CODAZZI',
            'ASTREA',
            'BECERRIL',
            'BOSCONIA',
            'CHIMICHAGUA',
            'CHIRIGUANA',
            'CURUMANI',
            'EL COPEY',
            'EL PASO',
            'GAMARRA',
            'GONZALEZ',
            'LA GLORIA',
            'LA JAGUA DE IBIRICO',
            'LAS PAZ',
            'MANAURE B CESAR',
            'PAILITAS',
            'PELAYA',
            'PUEBLO BELLO',
            'RIO DE ORO',
            'SAN ALBERTO',
            'SAN DIEGO',
            'SAN MARTIN',
            'TAMALAMEQUE',
            'VALLEDUPAR',
            'ACANDI',
            'ALTO BAUDO',
            'BAGADO',
            'BAHIA SOLANO',
            'BAJO BAUDO',
            'BAJO SAN JUAN',
            'BOJAYA',
            'CANTON DE SAN PABLO',
            'CONDOTO',
            'EL CARMEN',
            'EL LITORAL DE SAN JUAN',
            'ISTMINA',
            'JURADO',
            'LLORO',
            'NOVITA',
            'NUQUI',
            'QUIBDO',
            'RIOSUCIO',
            'SAN JOSE DE PALMAR',
            'SIPI',
            'TADO',
            'UNGRIA',
            'AYAPEL',
            'BUENAVISTA',
            'CANALETE',
            'CERETE',
            'CERROMATOSO',
            'CHINU',
            'CIENAGA DE ORO',
            'LORICA',
            'LOS CORDOBAS',
            'MOMIL',
            'MONTERIA',
            'MONITOS',
            'PLANETA RICA',
            'PUERTO ESCONDIDO',
            'PUERTO LIBERTADO',
            'PURISIMA',
            'SAHAGUN',
            'SAN ANDRES DE SOTAVENTO',
            'SAN ANTERO',
            'SAN BERNARDO DEL VIENTO',
            'SAN CARLOS',
            'SAN PELAYO',
            'TIERRALTA',
            'VALENCIA',
            'CHIMA',
            'MONTE LIBANO',
            'PUEBLO NUEVO',
            'GUTIERREZ',
            'MACHETA',
            'MEDINA',
            'TOPAIPI',
            'UTICA',
            'AGUA DE DIOS',
            'ALBAN',
            'ANAPOIMA',
            'ANOLAIMA',
            'APULO',
            'ARBELAEZ',
            'BELTRAN',
            'BITUIMA',
            'BOJACA',
            'CABRERA',
            'CACHIPAY',
            'CAJICA',
            'CAPARRAPI',
            'CAQUEZA',
            'CARMEN DE CARUPA',
            'CHAGUANI',
            'CHIA',
            'CHIPAQUE',
            'CHOACHI',
            'CHOCONTA',
            'COGUA',
            'COTA',
            'CUCUNUBA',
            'CUMACA',
            'EL COLEGIO',
            'EL PENON',
            'FACATATIVA',
            'FOMEQUE',
            'FOSCA',
            'FUNZA',
            'FUQUENE',
            'FUSAGASUGA',
            'GACHALA',
            'GACHANCIPA',
            'GACHETA',
            'GAMA',
            'GIRARDOT',
            'GRANADA',
            'GUACHETA',
            'GUADAS',
            'GUASCA',
            'GUATAQUI',
            'GUATAVITA',
            'GUAYABAL DE SIQUIMA',
            'GUAYABETAL',
            'JERUSALEN',
            'JUNIN',
            'LA CALERA',
            'LA MESA',
            'LA PALMA',
            'LA PENA',
            'LA VEGA',
            'LENGUAZAQUE',
            'MADRID',
            'MANTA',
            'MOSQUERA',
            'NARINO',
            'NEMOCON',
            'NILO',
            'NIMAIMA',
            'NOCAIMA',
            'PACHO',
            'PAIME',
            'PANDI',
            'PARATEBUENO',
            'PASCA',
            'PUERTO SALGAR',
            'PULI',
            'QUEBRADANEGRA',
            'QUETAME',
            'QUIPILE',
            'RICAURTE',
            'SAN ANTONIO DEL TEQUENDAMA',
            'SAN BERNARDO',
            'SAN CAYETANO',
            'SAN FRANCISCO',
            'SAN JUAN DE RIOSUCIO',
            'SASAIMA',
            'SESQUILE',
            'SIBATE',
            'SILVANIA',
            'SIMIJACA',
            'SOACHA',
            'SOPO',
            'SUBACHOQUE',
            'SUESCA',
            'SUPATA',
            'SUSA',
            'SUTATAUSA',
            'TABIO',
            'TAUSA',
            'TENA',
            'TENJO',
            'TIBACUY',
            'TIBIRITA',
            'TOCAIMA',
            'TOCANCIPA',
            'UBALA',
            'UBAQUE',
            'UBATE',
            'UNE',
            'URIBIA',
            'VENECIA',
            'VERGARA',
            'VIANI',
            'VILLAGOMEZ',
            'VILLAPINZON',
            'VILLETA',
            'VIOTA',
            'YACOPI',
            'ZIPACON',
            'ZIPAQUIRA',
            'GUAVIARE',
            'INIRIDA',
            'MIRAFLORES',
            'BARRANCAS',
            'DIBULLA',
            'DISTRACCION',
            'EL MOLINO',
            'FONSECA',
            'HATONUEVO',
            'MAICAO',
            'MANAURE',
            'PUERTO BOLIVAR',
            'RIOHACHA',
            'SAN JUAN CESAR',
            'URUMITA',
            'VILLANUEVA',
            'EL RETORNO',
            'MIRAFLORES',
            'MORICHAL VIEJO',
            'SAN JOSE DEL GUAVIARE',
            'ACEVEDO',
            'AGRADO',
            'AIPE',
            'ALGECIRAS',
            'ALTAMIRA',
            'BARAYA',
            'CAMPOALEGRE',
            'COLOMBIA',
            'ELIAS',
            'GARZON',
            'GIGANTE',
            'GUADALUPE',
            'HOBO',
            'IQUIRA',
            'ISNOS',
            'LA ARGENTINA',
            'LA PLATA',
            'NATAGA',
            'NEIVA',
            'OPORAPA',
            'PAICOL',
            'PALERMO',
            'PALESTINA',
            'PITAL',
            'PITALITO',
            'RIVERA',
            'SALADOBLANCO',
            'SAN AGUSTIN',
            'SANTA MARIA',
            'SUAZA',
            'TARQUI',
            'TELLO',
            'TERUEL',
            'TESALIA',
            'TIMANA',
            'VEGA LARGA',
            'VILLAVIEJA',
            'YAGUARA',
            'ARACATACA',
            'CERRO SAN ANTONIO',
            'CHIVOLO',
            'CIENAGA',
            'EL BANCO',
            'EL DIFICIL',
            'EL PINON',
            'EL RETEN',
            'FUNDACION',
            'GUAMAL',
            'PEDRAZA',
            'PIJINO DEL CARMEN',
            'PIVIJAY',
            'PLATO',
            'PUEBLOVIEJO',
            'REMOLINO',
            'SALAMINA',
            'SAN SEBASTIAN BUENAVISTA',
            'SAN ZENON',
            'SANTA ANA',
            'SANTA MARTA',
            'SITIONUEVO',
            'TENERIFE',
            'ACACIAS',
            'BARRANCA DE UPIA',
            'CABUYARO',
            'CASTILLA NUEVA',
            'CUBARRAL',
            'CUMARAL',
            'EL CALVARIO',
            'EL CASTILLO',
            'EL DORADO',
            'FUENTE DE ORO',
            'GRANADA',
            'GUAMAL',
            'LA MACARENA',
            'LA URIBE',
            'LEJANIAS',
            'MAPIRIPAN',
            'MEDELLIN DEL ARIARI',
            'MEDINA',
            'MESETAS',
            'PUERTO CONCORDIA',
            'PUERTO GAITAN',
            'PUERTO LLERAS',
            'PUERTO LOPEZ',
            'PUERTO RICO',
            'RESTREPO',
            'SAN CARLOS GUAR',
            'SAN JUAN DE ARAMA',
            'SAN JUANITO',
            'SAN MARTIN',
            'VILLAVICENCIO',
            'VISTA HERMOSA',
            'ALBAN',
            'ALDANA',
            'ANCUYA',
            'ARBOLEDA',
            'BARBACOAS',
            'BELEN',
            'BUESACO',
            'CHACHAGUI',
            'COLON',
            'CONSACA',
            'CONTADERO',
            'CORDOBA',
            'CUASPUD',
            'CUMBAL',
            'CUMBITARA',
            'EL CHARCO',
            'EL ROSARIO',
            'EL TABLON',
            'EL TAMBO',
            'FRANCISCO PIZARRO',
            'FUNES',
            'GUACHUCAL',
            'GUAITARILLA',
            'GUALMATAN',
            'IMUES',
            'IPIALES',
            'LA CRUZ',
            'LA FLORIDA',
            'LA LLANADA',
            'LA TOLA',
            'LA UNION',
            'LEIVA',
            'LINARES',
            'LLES',
            'LOS ANDES',
            'MAGUI',
            'MALLANA',
            'MOSQUERA',
            'OLAYA HERRERA',
            'OSPINA',
            'PASTO',
            'POLICARPA',
            'POTOSI',
            'PROVIDENCIA',
            'PUERRES',
            'PUPIALES',
            'RICAURTE',
            'ROBERTO PAYAN',
            'SAMANIEGO',
            'SAN BERNARDO',
            'SAN LORENZO',
            'SAN PABLO',
            'SAN PEDRO DE CARTAGO',
            'SANDONA',
            'SANTA BARBARA',
            'SANTA CRUZ',
            'SAPUYES',
            'TAMINANGO',
            'TANGUA',
            'TUMACO',
            'TUQUERRES',
            'YACUANQUER',
            'ABREGO',
            'ARBOLEDAS',
            'BOCHALEMA',
            'BUCARASICA',
            'CACOTA',
            'CHACHIRA',
            'CHINACOTA',
            'CHITAGA',
            'CONVENCION',
            'CUCUTA',
            'CUCUTILLA',
            'DURANIA',
            'EL CARMEN',
            'EL TARRA',
            'EL ZULIA',
            'GIBRALTAR',
            'GRAMALOTE',
            'HACARI',
            'HERRAN',
            'LA ESPERANZA',
            'LA GABARRA',
            'LA PLAYA',
            'LA VEGA',
            'LABATECA',
            'LAS MERCDEDES',
            'LOS PATIOS',
            'LOURDES',
            'MUTISCUA',
            'OCANA',
            'PAMPLONA',
            'PAMPLONITA',
            'PUERTO SANTANDER',
            'RAGONVALIA',
            'SALAZAR',
            'SAN CALIXTO',
            'SAN CAYETANO',
            'SANTIAGO',
            'SARDINATA',
            'SILOS',
            'TEORAMA',
            'TIBU',
            'TOLEDO',
            'VILLA CARO',
            'VILLA ROSARIO',
            'COLON',
            'MOCOA',
            'ORITO',
            'PUERTO ASIS',
            'PUERTO LEGUIZAMO',
            'SAN FRANCISCO',
            'SANTIAGO',
            'SIBUNDOY',
            'VALLE DE GUAMUEZ',
            'VILLAGARZON',
            'PIJAO',
            'ARMENIA',
            'BUENAVISTA',
            'CALARCA',
            'CIRCASIA',
            'CORDOBA',
            'FILANDIA',
            'GENOVA',
            'LA TEBAIDA',
            'MONTENEGRO',
            'QUIMBAYA',
            'SALENTO',
            'APIA',
            'BALBOA',
            'BELEN DE UMBRIA',
            'BETULIA',
            'DOSQUEBRADAS',
            'GUATICA',
            'LA CELIA',
            'LA VIRGINIA',
            'MARSELLA',
            'MISTRATO',
            'PEREIRA',
            'PUEBLO RICO',
            'QUINCHIA',
            'SANTA ROSA DE CABAL',
            'SANTUARIO',
            'PROVIDENCIA',
            'SAN ANDRES',
            'AGUADA',
            'ALBANIA',
            'ARATOCA',
            'BARBOSA',
            'BARICHARA',
            'BARRANCABERMEJA',
            'BOLIVAR',
            'BUCARAMANGA',
            'CABRERA',
            'CALIFORNIA',
            'CAPITANEJO',
            'CARCASI',
            'CEPITA',
            'CERRITO',
            'CHARALA',
            'CHARTA',
            'CHIMA',
            'CHIPATA',
            'CIMITARRA',
            'CONCEPCION',
            'CONFINES',
            'CONTRATACION',
            'COROMOTO',
            'CURITI',
            'EL CARMEN',
            'EL CENTRO',
            'EL GUACAMAYO',
            'EL PENON',
            'EL PLAYON',
            'ENCINO',
            'ENCISO',
            'FLORIAN',
            'FLORIDABLANCA',
            'GALAN',
            'GAMBITA',
            'GIRON',
            'GUACA',
            'GUADALUPE',
            'GUAPOTA',
            'GUAVATA',
            'GUEPSA',
            'HATO',
            'JESUS MARIA',
            'JORDAN',
            'LA BELLEZA',
            'LA PAZ',
            'LANDAZURI',
            'LEBRIJA',
            'LOS SANTOS',
            'MACARAVITA',
            'MALAGA',
            'MATANZA',
            'MOGOTES',
            'MOLAGAVITA',
            'OCAMONTE',
            'OIBA',
            'ONZAGA',
            'PALMAR',
            'PALMAS DEL SOCORRRO',
            'PARAMO',
            'PIEDECUESTA',
            'PINCHOTE',
            'PUENTE NACIONAL',
            'PUERTO PARRA',
            'PUERTO WILCHES',
            'RIONEGRO',
            'SABANA DE TORRES',
            'SAN ANDRES',
            'SAN BENITO',
            'SAN FRANCISCO',
            'SAN GIL',
            'SAN JOAQUIN',
            'SAN JOSE DE S',
            'SAN JOSEMIRANDA',
            'SAN MIGUEL',
            'SAN VICENTE DE CHUCURY',
            'SANTA BARBARA',
            'SANTA HELENA DEL OPION',
            'SIMACOTA',
            'SOCORRO',
            'SUAITA',
            'SUCRE',
            'SURATA',
            'TONA',
            'VALLE SAN JOSE',
            'VELEZ',
            'VETAS',
            'VILLANUEVA',
            'ZAPATOCA',
            'BUENAVISTA',
            'CAIMITO',
            'CHALAN',
            'COLOSO',
            'COROZAL',
            'GALERAS',
            'GUARANDA',
            'LA UNION',
            'LOS PALMITOS',
            'MAJAGUAL',
            'MORROA',
            'OVEJAS',
            'PALMITO',
            'SAMPUES',
            'SAN BENITO ABAD',
            'SAN JUAN BETULIA',
            'SAN MARCOS',
            'SAN ONOFRE',
            'SAN PEDRO',
            'SINCE',
            'SINCELEJO',
            'SUCRE',
            'TOLU',
            'TOLUVIEJO',
            'ALPUJARRA',
            'ALVARADO',
            'AMBALEMA',
            'ANZOATEQUI',
            'ARMERO',
            'ATACO',
            'CADIZ',
            'CAJAMARCA',
            'CARMEN DE APICALA',
            'CASABLANCA',
            'CHAPARRAL',
            'CHICORAL',
            'COELLO',
            'COYAIMA',
            'CUNDAY',
            'DOLORES',
            'ESPINAL',
            'FALAN',
            'FLANDES',
            'FRESNO',
            'GAITANA',
            'GUAMO',
            'HERRERA',
            'HERVEO',
            'HONDA',
            'IBAGUE',
            'ICONONZO',
            'JUNIN',
            'LERIDA',
            'LIBANO',
            'MARIQUITA',
            'MELGAR',
            'MURILLO',
            'NATAGAIMA',
            'ORTEGA',
            'PALO CABILDO',
            'PIEDRAS',
            'PLANADAS',
            'PLAYARICA',
            'PRADO',
            'PURIFICACION',
            'RIOBLANCO',
            'RONCESVALLES',
            'ROVIRA',
            'SALDANA',
            'SAN ANTONIO',
            'SAN LUIS',
            'SANTA ISABEL',
            'SANTA TERESA',
            'SANTIAGO PEREZ',
            'SUAREZ',
            'TRES ESQUINAS',
            'VALLE DE SAN JUAN',
            'VENADILLO',
            'VILLAHERMOSA',
            'VILLARICA',
            'ALCALA',
            'ANDALUCIA',
            'ANSERMANUEVO',
            'ARGELIA',
            'BOLIVAR',
            'BUENAVENTURA',
            'BUGA',
            'BUGALAGRANDE',
            'CAICEDONIA',
            'CALI',
            'CANDELARIA',
            'CARTAGO',
            'DAGUA',
            'DARIEN',
            'EL AGUILA',
            'EL CAIRO',
            'EL CERRITO',
            'EL DOVIO',
            'FLORIDA',
            'GINEBRA',
            'GUACARI',
            'JAMUNDI',
            'LA CUMBRE',
            'LA UNION',
            'LA VICTORIA',
            'OBANDO',
            'PALMIRA',
            'PRADERA',
            'RESTREPO',
            'RIOFRIO',
            'ROLDANILLO',
            'SAN PEDRO',
            'SEVILLA',
            'TORO',
            'TRUJILLO',
            'TULUA',
            'ULLOA',
            'VERSALLES',
            'VIJES',
            'YOTOCO',
            'YUMBO',
            'ZARZAL',
            'CARURU',
            'MITU',
            'PACOA',
            'YAVARATE',
            'NUEVA ANTIOQUIA',
            'PRIMAVERA',
            'PUERTO CARRENO',
            'SAN JOSE OCUPE',];
        $products = json_decode($client->request('GET',
            $baseUrl . '?operation=describe&sessionName=' . $sessionName . '&elementType=Potentials')->getBody())->result->fields;
        $accounts = $this->getFieldsToShow(json_decode($client->request('GET',
            $baseUrl . '?operation=describe&sessionName=' . $sessionName . '&elementType=Accounts')->getBody())->result->fields);
        $users = json_decode($client->request('GET',
            $baseUrl . '?operation=query&sessionName=' . $sessionName . '&query=select * from Users;')->getBody())->result;
        $medicines = json_decode($client->request('GET',
            $baseUrl . '?operation=query&sessionName=' . $sessionName . '&query=select * from Potentials;')->getBody())->result;
        return view('layouts.welcome', compact(['products', 'accounts', 'users', 'medicines', 'cities', 'currentTime']));
    }

    /**
     * @param \Illuminate\Http\Request $request
     */
    public function store(RequestAlias $request) {
        $baseUrl = 'https://server3.datacrm.la/datacrm/sanofi/webservice.php';
        $data = $request->all();
        $client = new Client(
            [
                'defaults' => [
                    'headers'  => [
                        'content-type' => 'application/x-www-form-urlencoded',
                        'Accept' => 'application/json'
                    ],
                ],
            ]
        );
        $sessionname = $this->getSessionName();
        try{
            $request = $client->request('POST', $baseUrl,  [
                'form_params' => [
                    'elementType'=> 'Products',
                    'operation' => 'create',
                    'element' => urlencode(json_encode($data)),
                    'sessionName'=> $sessionname
                ]
            ]);
            return redirect()->route('front');
        }catch (ExceptionAlias $e){

        }
    }

    public function account(RequestAlias $request){
        $baseUrl = 'https://server3.datacrm.la/datacrm/sanofi/webservice.php';
        $data = $request->all();
        $data['assigned_user_id'] = '19x' . $data['assigned_user_id'];
        $data['siccode'] = (int)$data['siccode'];

        $client = new Client(
            [
                'defaults' => [
                    'headers'  => [
                        'content-type' => 'application/x-www-form-urlencoded',
                        'Accept' => 'application/json'
                    ],
                ],
            ]
        );
        $sessionname = $this->getSessionName();

        try{
            $request = $client->request('POST', $baseUrl,  [
                'form_params' => [
                    'elementType'=> 'Accounts',
                    'operation' => 'create',
                    'element' => json_encode($data),
                    'sessionName'=> $sessionname
                ]
            ]);
            if($data['rating'] !== 'Preinscrito'){
                try{
                    $accountUser = json_decode($request->getBody());
                    $datapreinscrito['potentialname'] = $data['potentialname'];
                    $datapreinscrito['related_to'] = $accountUser->id;
                    $datapreinscrito['assigned_user_id'] = $accountUser->assigned_user_id;
                    $request = $client->request('POST', $baseUrl,  [
                        'form_params' => [
                            'elementType'=> 'Potentials',
                            'operation' => 'create',
                            'element' => json_encode($datapreinscrito),
                            'sessionName'=> $sessionname
                        ]
                    ]);
                    return redirect()->route('front');
                }catch (\Exception $exception){

                }
            }else{
                return redirect()->route('front');
            }
        }catch (ExceptionAlias $e){

        }
    }

    public function helpdesk() {
        $currentTime = Carbon::now()->format('Y-m-d');
        $baseUrl = 'https://server3.datacrm.la/datacrm/sanofi/webservice.php';
        $client = new Client(
            [
                'defaults' => [
                    'headers'  => [
                        'content-type' => 'application/x-www-form-urlencoded',
                        'Accept' => 'application/json'
                    ],
                ],
            ]
        );
        $sessionName = $this->getSessionName();
        $cities = ['EL ENCANTO',
            'LA CHORRERA',
            'LA PRADERA',
            'LETICIA',
            'MIRITI',
            'PUERTO NARINO',
            'PUERTO SANTANDER',
            'TARAPACA',
            'ABEJORRAL',
            'ABRIAQUI',
            'ALEJANDRIA',
            'ALTAMIRA',
            'AMAGA',
            'AMALFI',
            'ANDES',
            'ANGELOPOLIS',
            'ANGOSTURA',
            'ANORI',
            'ANTIOQUIA',
            'ANZA',
            'APARTADO',
            'ARBOLETES',
            'ARGELIA',
            'ARMENIA',
            'BARBOSA',
            'BELLO',
            'BELMIRA',
            'BETANIA',
            'BETULIA',
            'BOLIVAR',
            'BRICENO',
            'BURITICA',
            'CACERES',
            'CAICEDO',
            'CALDAS',
            'CAMPAMENTO',
            'CANAS GORDAS',
            'CARACOLI',
            'CARAMANTA',
            'CAREPA',
            'CARMEN DE VIBORAL',
            'CAROLINA',
            'CAUCASIA',
            'CHIGORODO',
            'CISNEROS',
            'COCORNA',
            'CONCEPCION',
            'COPACABANA',
            'DABEIBA',
            'DON MATIAS',
            'EBEJICO',
            'EL BAGRE',
            'ENTRERRIOS',
            'ENVIGADO',
            'FREDONIA',
            'FRONTINO',
            'GIRALDO',
            'GIRARDOTA',
            'GOMEZ PLATA',
            'GRANADA',
            'GUADALUPE',
            'GUARNE',
            'GUATAPE',
            'HELICONIA',
            'HISPANIA',
            'ITAGUI',
            'ITUANGO',
            'JARDIN',
            'JERICO',
            'LA CEJA',
            'LA ESTRELLA',
            'LA UNION',
            'LIBORINA',
            'MACEO',
            'MARINILLA',
            'MEDELLIN',
            'MONTEBELLO',
            'MURINDO',
            'MUTATA',
            'NARINO',
            'NECHI',
            'NECOCLI',
            'OLAYA',
            'PENOL',
            'PEQUE',
            'PUEBLO RICO',
            'PUERTO BERRIO',
            'PUERTO NARE',
            'PUERTO TRIUNFO',
            'REMEDIOS',
            'RETIRO',
            'RIONEGRO',
            'SABANALARGA',
            'SABANETA',
            'SALGAR',
            'SAN ANDRES',
            'SAN CARLOS',
            'SAN CRISTOBAL',
            'SAN FRANCISCO',
            'SAN JERONIMO',
            'SAN JOSE DE MONTANA',
            'SAN JUAN DE URABA',
            'SAN LUIS',
            'SAN PEDRO',
            'SAN PEDRO DE URABA',
            'SAN RAFAEL',
            'SAN ROQUE',
            'SAN VICENTE',
            'SANTA BARBARA',
            'SANTA ROSA DE OSOS',
            'SANTO DOMINGO',
            'SANTUARIO',
            'SEGOVIA',
            'SONSON',
            'SOPETRAN',
            'TAMESIS',
            'TARAZA',
            'TARSO',
            'TITIRIBI',
            'TOLEDO',
            'TURBO',
            'URAMITA',
            'URRAO',
            'VALDIVIA',
            'VALPARAISO',
            'VEGACHI',
            'VENECIA',
            'VIGIA DEL FUERTE',
            'YALI',
            'YARUMAL',
            'YOLOMBO',
            'YONDO',
            'ZARAGOZA',
            'ARAUCA',
            'ARAUQUITA',
            'CRAVO NORTE',
            'FORTUL',
            'SARAVENA',
            'TAME',
            'BARANOA',
            'BARRANQUILLA',
            'CAMPO DE CRUZ',
            'CANDELARIA',
            'GALAPA',
            'LURUACO',
            'MALAMBO',
            'MANATI',
            'PALMAR VARELA',
            'PIOJO',
            'POLONUEVO',
            'PONEDERA',
            'PUERTO COLOMBIA',
            'REPELON',
            'SABANAGRANDE',
            'SABANALARGA',
            'SANTA LUCIA',
            'SANTO TOMAS',
            'SOLEDAD',
            'SUAN',
            'TUBARA',
            'USIACURI',
            'BOGOTA',
            'ACHI',
            'ALT DEL ROSARIO',
            'ARJONA',
            'BARRANCO DE LOBA',
            'CALAMAR',
            'CANTAGALLO',
            'CARMEN DE BOLIVAR',
            'CARTAGENA',
            'CICUCO',
            'CLEMENCIA',
            'CORDOBA',
            'EL GUAMO',
            'EL PENON',
            'HATILLO DE LOBA',
            'MAGANGUE',
            'MAHATES',
            'MARGARITA',
            'MARIA LA BAJA',
            'MOMPOS',
            'MONTECRISTO',
            'MORALES',
            'PINILLOS',
            'REGIDOR',
            'RIO VIEJO',
            'SAN CRISTOBAL',
            'SAN ESTANISLAO',
            'SAN FERNANDO',
            'SAN JACINTO',
            'SAN JUAN NEPOMUCENO',
            'SAN MARTIN DE LOBA',
            'SAN PABLO',
            'SANTA CATALINA',
            'SANTA ROSA',
            'SANTA ROSA SUR',
            'SIMITI',
            'SOPLAVIENTO',
            'TALAIGUA NUEVO',
            'TIQUISIO',
            'TURBACO',
            'TURBANA',
            'VILLANUEVA',
            'ZAMBRANO',
            'ALMEIDA',
            'AQUITANIA',
            'ARCABUCO',
            'BELEN',
            'BELENCITO',
            'BERBEO',
            'BETETIVA',
            'BOAVITA',
            'BOYACA',
            'BRICENO',
            'BUENAVISTA',
            'BUSBANZA',
            'CALDAS',
            'CAMPOHERMOSO',
            'CERINZA',
            'CHINAVITA',
            'CHIQUINQUIRA',
            'CHIQUIZA',
            'CHISCAS',
            'CHITA',
            'CHITARAQUE',
            'CHIVATA',
            'CHIVOR',
            'CIENAGA',
            'COMBITA',
            'COPER',
            'CORRALES',
            'COVARACHIA',
            'CUBARA',
            'CUCAITA',
            'CUITIVA',
            'DUITAMA',
            'EL COCUY',
            'EL ESPINO',
            'FIRAVITOBA',
            'FLORESTA',
            'GACHANTIVA',
            'GAMEZA',
            'GARAGOA',
            'GUACAMAYAS',
            'GUATEQUE',
            'GUAYATA',
            'GUICAN',
            'IZA',
            'JENESANO',
            'JERICO',
            'LA CAPILLA',
            'LA UVITA',
            'LA VICTORIA',
            'LABRANZAGRANDE',
            'MACANAL',
            'MARIPI',
            'MIRAFLORES',
            'MONGUA',
            'MONGUI',
            'MONIQUIRA',
            'MOTAVITA',
            'MUZO',
            'NOBSA',
            'NUEVO COLON',
            'OICATA',
            'OTANCHE',
            'PACHAVITA',
            'PAEZ',
            'PAIPA',
            'PAJARITO',
            'PANQUEBA',
            'PAUNA',
            'PAYA',
            'PAZ DEL RIO',
            'PESCA',
            'PISBA',
            'PUERTO BOYACA',
            'QUIPAMA',
            'RAMIRIQUI',
            'RAQUIRA',
            'RONDON',
            'SABOYA',
            'SACHICA',
            'SAMACA',
            'SAN EDUARDO',
            'SAN JOSE DE PARE',
            'SAN LUIS DE GACENO',
            'SAN MATEO',
            'SAN MIGUEL DE SEMA',
            'SAN PABLO DE BORBUR',
            'SANTA MARIA',
            'SANTA ROSA DE VITERBO',
            'SANTA SOFIA',
            'SANTANA',
            'SATIVA NORTE',
            'SATIVA SUR',
            'SIACHOQUE',
            'SOATA',
            'SOCHA',
            'SOCOTA',
            'SOGAMOSO',
            'SOMONDOCO',
            'SORA',
            'SORACA',
            'SOTAQUIRA',
            'SUSACON',
            'SUTAMARCHAN',
            'SUTATENZA',
            'TAPAGA',
            'TASCO',
            'TENZA',
            'TIBANA',
            'TIBASOSA',
            'TINJACA',
            'TIPACOQUE',
            'TOCA',
            'TOGUI',
            'TOTA',
            'TUNJA',
            'TUNUNGUA',
            'TURMEQUE',
            'TUTA',
            'TUTASA',
            'UMBITA',
            'VENTAQUEMADA',
            'VILLA DE LEYVA',
            'VIRACACHA',
            'ZETAQUIRA',
            'AGUADAS',
            'ANSERMA',
            'ARANZAZU',
            'ARAUCA',
            'ARBOLEDA',
            'BELALCAZAR',
            'BOLIVIA',
            'CHINCHINA',
            'FILADELFIA',
            'FLORENCIA',
            'LA DORADA',
            'LA MERCED',
            'MANIZALES',
            'MANZANARES',
            'MARMATO',
            'MARQUETALIA',
            'MARULANDA',
            'MONTEBONITO',
            'NEIRA',
            'NORCASIA',
            'PACORA',
            'PALESTINA',
            'PENSILVANIA',
            'RIOSUCIO',
            'RISARALDA',
            'SALAMINA',
            'SAMANA',
            'SAN FELIX',
            'SAN JOSE DE RISARALDA',
            'SUPIA',
            'VICTORIA',
            'VILLA MARIA',
            'VITERBO',
            'ALBANIA',
            'BELEN ANDAQUI',
            'CARTAGENA DEL CHAIRA',
            'CURILLO',
            'EL DONCELLO',
            'EL PAUJIL',
            'FLORENCIA',
            'GUACAMAYAS',
            'LA MONTANITA',
            'MATICURO',
            'MILAN',
            'MORELLA',
            'PUERTO RICO',
            'SAN JOSE FRAGUA',
            'SAN VICENTE CAGUAN',
            'SOLANO',
            'SOLITA',
            'VALPARAISO',
            'AGUAZUL',
            'CHAMEZA',
            'HATOM COROZAL',
            'LA SALINA',
            'MANI',
            'MONTERREY',
            'NUNCHIA',
            'OROCUE',
            'PAZ DE ARIPORO',
            'PORE',
            'RECETOR',
            'SABANALARGA',
            'SACAMA',
            'SAN LUIS PALENQUE',
            'TAMARA',
            'TAURAMENA',
            'TRINIDAD',
            'VILLA NUEVA',
            'YOPAL',
            'ALMAGUER',
            'ARGELIA',
            'BALBOA',
            'BOLIVAR',
            'BUENOS AIRES',
            'CAJIBIO',
            'CALDONO',
            'CALOTO',
            'CORINTO',
            'EL TAMBO',
            'FLORENCIA',
            'GUAPI',
            'INZA',
            'JAMBALO',
            'LA SIERRA',
            'LA VEGA',
            'LOPEZ DE MICAY',
            'MERCADERES',
            'MIRANDA',
            'MORALES',
            'PADILLA',
            'PAEZ',
            'PATIA',
            'PIAMONTE',
            'PIENDAMO',
            'POPAYAN',
            'PUERTO TEJADA',
            'PURACE',
            'ROSAS',
            'SAN SEBASTIAN',
            'SANTA ROSA',
            'SANTANDER',
            'SANTANDER DE QUILICHAO',
            'SIBERIA',
            'SILVIA',
            'SOTARA',
            'SUAREZ',
            'TIMBIO',
            'TIMBIQUI',
            'TORIBIO',
            'TOTORO',
            'AGUACHICA',
            'AGUSTIN CODAZZI',
            'ASTREA',
            'BECERRIL',
            'BOSCONIA',
            'CHIMICHAGUA',
            'CHIRIGUANA',
            'CURUMANI',
            'EL COPEY',
            'EL PASO',
            'GAMARRA',
            'GONZALEZ',
            'LA GLORIA',
            'LA JAGUA DE IBIRICO',
            'LAS PAZ',
            'MANAURE B CESAR',
            'PAILITAS',
            'PELAYA',
            'PUEBLO BELLO',
            'RIO DE ORO',
            'SAN ALBERTO',
            'SAN DIEGO',
            'SAN MARTIN',
            'TAMALAMEQUE',
            'VALLEDUPAR',
            'ACANDI',
            'ALTO BAUDO',
            'BAGADO',
            'BAHIA SOLANO',
            'BAJO BAUDO',
            'BAJO SAN JUAN',
            'BOJAYA',
            'CANTON DE SAN PABLO',
            'CONDOTO',
            'EL CARMEN',
            'EL LITORAL DE SAN JUAN',
            'ISTMINA',
            'JURADO',
            'LLORO',
            'NOVITA',
            'NUQUI',
            'QUIBDO',
            'RIOSUCIO',
            'SAN JOSE DE PALMAR',
            'SIPI',
            'TADO',
            'UNGRIA',
            'AYAPEL',
            'BUENAVISTA',
            'CANALETE',
            'CERETE',
            'CERROMATOSO',
            'CHINU',
            'CIENAGA DE ORO',
            'LORICA',
            'LOS CORDOBAS',
            'MOMIL',
            'MONTERIA',
            'MONITOS',
            'PLANETA RICA',
            'PUERTO ESCONDIDO',
            'PUERTO LIBERTADO',
            'PURISIMA',
            'SAHAGUN',
            'SAN ANDRES DE SOTAVENTO',
            'SAN ANTERO',
            'SAN BERNARDO DEL VIENTO',
            'SAN CARLOS',
            'SAN PELAYO',
            'TIERRALTA',
            'VALENCIA',
            'CHIMA',
            'MONTE LIBANO',
            'PUEBLO NUEVO',
            'GUTIERREZ',
            'MACHETA',
            'MEDINA',
            'TOPAIPI',
            'UTICA',
            'AGUA DE DIOS',
            'ALBAN',
            'ANAPOIMA',
            'ANOLAIMA',
            'APULO',
            'ARBELAEZ',
            'BELTRAN',
            'BITUIMA',
            'BOJACA',
            'CABRERA',
            'CACHIPAY',
            'CAJICA',
            'CAPARRAPI',
            'CAQUEZA',
            'CARMEN DE CARUPA',
            'CHAGUANI',
            'CHIA',
            'CHIPAQUE',
            'CHOACHI',
            'CHOCONTA',
            'COGUA',
            'COTA',
            'CUCUNUBA',
            'CUMACA',
            'EL COLEGIO',
            'EL PENON',
            'FACATATIVA',
            'FOMEQUE',
            'FOSCA',
            'FUNZA',
            'FUQUENE',
            'FUSAGASUGA',
            'GACHALA',
            'GACHANCIPA',
            'GACHETA',
            'GAMA',
            'GIRARDOT',
            'GRANADA',
            'GUACHETA',
            'GUADAS',
            'GUASCA',
            'GUATAQUI',
            'GUATAVITA',
            'GUAYABAL DE SIQUIMA',
            'GUAYABETAL',
            'JERUSALEN',
            'JUNIN',
            'LA CALERA',
            'LA MESA',
            'LA PALMA',
            'LA PENA',
            'LA VEGA',
            'LENGUAZAQUE',
            'MADRID',
            'MANTA',
            'MOSQUERA',
            'NARINO',
            'NEMOCON',
            'NILO',
            'NIMAIMA',
            'NOCAIMA',
            'PACHO',
            'PAIME',
            'PANDI',
            'PARATEBUENO',
            'PASCA',
            'PUERTO SALGAR',
            'PULI',
            'QUEBRADANEGRA',
            'QUETAME',
            'QUIPILE',
            'RICAURTE',
            'SAN ANTONIO DEL TEQUENDAMA',
            'SAN BERNARDO',
            'SAN CAYETANO',
            'SAN FRANCISCO',
            'SAN JUAN DE RIOSUCIO',
            'SASAIMA',
            'SESQUILE',
            'SIBATE',
            'SILVANIA',
            'SIMIJACA',
            'SOACHA',
            'SOPO',
            'SUBACHOQUE',
            'SUESCA',
            'SUPATA',
            'SUSA',
            'SUTATAUSA',
            'TABIO',
            'TAUSA',
            'TENA',
            'TENJO',
            'TIBACUY',
            'TIBIRITA',
            'TOCAIMA',
            'TOCANCIPA',
            'UBALA',
            'UBAQUE',
            'UBATE',
            'UNE',
            'URIBIA',
            'VENECIA',
            'VERGARA',
            'VIANI',
            'VILLAGOMEZ',
            'VILLAPINZON',
            'VILLETA',
            'VIOTA',
            'YACOPI',
            'ZIPACON',
            'ZIPAQUIRA',
            'GUAVIARE',
            'INIRIDA',
            'MIRAFLORES',
            'BARRANCAS',
            'DIBULLA',
            'DISTRACCION',
            'EL MOLINO',
            'FONSECA',
            'HATONUEVO',
            'MAICAO',
            'MANAURE',
            'PUERTO BOLIVAR',
            'RIOHACHA',
            'SAN JUAN CESAR',
            'URUMITA',
            'VILLANUEVA',
            'EL RETORNO',
            'MIRAFLORES',
            'MORICHAL VIEJO',
            'SAN JOSE DEL GUAVIARE',
            'ACEVEDO',
            'AGRADO',
            'AIPE',
            'ALGECIRAS',
            'ALTAMIRA',
            'BARAYA',
            'CAMPOALEGRE',
            'COLOMBIA',
            'ELIAS',
            'GARZON',
            'GIGANTE',
            'GUADALUPE',
            'HOBO',
            'IQUIRA',
            'ISNOS',
            'LA ARGENTINA',
            'LA PLATA',
            'NATAGA',
            'NEIVA',
            'OPORAPA',
            'PAICOL',
            'PALERMO',
            'PALESTINA',
            'PITAL',
            'PITALITO',
            'RIVERA',
            'SALADOBLANCO',
            'SAN AGUSTIN',
            'SANTA MARIA',
            'SUAZA',
            'TARQUI',
            'TELLO',
            'TERUEL',
            'TESALIA',
            'TIMANA',
            'VEGA LARGA',
            'VILLAVIEJA',
            'YAGUARA',
            'ARACATACA',
            'CERRO SAN ANTONIO',
            'CHIVOLO',
            'CIENAGA',
            'EL BANCO',
            'EL DIFICIL',
            'EL PINON',
            'EL RETEN',
            'FUNDACION',
            'GUAMAL',
            'PEDRAZA',
            'PIJINO DEL CARMEN',
            'PIVIJAY',
            'PLATO',
            'PUEBLOVIEJO',
            'REMOLINO',
            'SALAMINA',
            'SAN SEBASTIAN BUENAVISTA',
            'SAN ZENON',
            'SANTA ANA',
            'SANTA MARTA',
            'SITIONUEVO',
            'TENERIFE',
            'ACACIAS',
            'BARRANCA DE UPIA',
            'CABUYARO',
            'CASTILLA NUEVA',
            'CUBARRAL',
            'CUMARAL',
            'EL CALVARIO',
            'EL CASTILLO',
            'EL DORADO',
            'FUENTE DE ORO',
            'GRANADA',
            'GUAMAL',
            'LA MACARENA',
            'LA URIBE',
            'LEJANIAS',
            'MAPIRIPAN',
            'MEDELLIN DEL ARIARI',
            'MEDINA',
            'MESETAS',
            'PUERTO CONCORDIA',
            'PUERTO GAITAN',
            'PUERTO LLERAS',
            'PUERTO LOPEZ',
            'PUERTO RICO',
            'RESTREPO',
            'SAN CARLOS GUAR',
            'SAN JUAN DE ARAMA',
            'SAN JUANITO',
            'SAN MARTIN',
            'VILLAVICENCIO',
            'VISTA HERMOSA',
            'ALBAN',
            'ALDANA',
            'ANCUYA',
            'ARBOLEDA',
            'BARBACOAS',
            'BELEN',
            'BUESACO',
            'CHACHAGUI',
            'COLON',
            'CONSACA',
            'CONTADERO',
            'CORDOBA',
            'CUASPUD',
            'CUMBAL',
            'CUMBITARA',
            'EL CHARCO',
            'EL ROSARIO',
            'EL TABLON',
            'EL TAMBO',
            'FRANCISCO PIZARRO',
            'FUNES',
            'GUACHUCAL',
            'GUAITARILLA',
            'GUALMATAN',
            'IMUES',
            'IPIALES',
            'LA CRUZ',
            'LA FLORIDA',
            'LA LLANADA',
            'LA TOLA',
            'LA UNION',
            'LEIVA',
            'LINARES',
            'LLES',
            'LOS ANDES',
            'MAGUI',
            'MALLANA',
            'MOSQUERA',
            'OLAYA HERRERA',
            'OSPINA',
            'PASTO',
            'POLICARPA',
            'POTOSI',
            'PROVIDENCIA',
            'PUERRES',
            'PUPIALES',
            'RICAURTE',
            'ROBERTO PAYAN',
            'SAMANIEGO',
            'SAN BERNARDO',
            'SAN LORENZO',
            'SAN PABLO',
            'SAN PEDRO DE CARTAGO',
            'SANDONA',
            'SANTA BARBARA',
            'SANTA CRUZ',
            'SAPUYES',
            'TAMINANGO',
            'TANGUA',
            'TUMACO',
            'TUQUERRES',
            'YACUANQUER',
            'ABREGO',
            'ARBOLEDAS',
            'BOCHALEMA',
            'BUCARASICA',
            'CACOTA',
            'CHACHIRA',
            'CHINACOTA',
            'CHITAGA',
            'CONVENCION',
            'CUCUTA',
            'CUCUTILLA',
            'DURANIA',
            'EL CARMEN',
            'EL TARRA',
            'EL ZULIA',
            'GIBRALTAR',
            'GRAMALOTE',
            'HACARI',
            'HERRAN',
            'LA ESPERANZA',
            'LA GABARRA',
            'LA PLAYA',
            'LA VEGA',
            'LABATECA',
            'LAS MERCDEDES',
            'LOS PATIOS',
            'LOURDES',
            'MUTISCUA',
            'OCANA',
            'PAMPLONA',
            'PAMPLONITA',
            'PUERTO SANTANDER',
            'RAGONVALIA',
            'SALAZAR',
            'SAN CALIXTO',
            'SAN CAYETANO',
            'SANTIAGO',
            'SARDINATA',
            'SILOS',
            'TEORAMA',
            'TIBU',
            'TOLEDO',
            'VILLA CARO',
            'VILLA ROSARIO',
            'COLON',
            'MOCOA',
            'ORITO',
            'PUERTO ASIS',
            'PUERTO LEGUIZAMO',
            'SAN FRANCISCO',
            'SANTIAGO',
            'SIBUNDOY',
            'VALLE DE GUAMUEZ',
            'VILLAGARZON',
            'PIJAO',
            'ARMENIA',
            'BUENAVISTA',
            'CALARCA',
            'CIRCASIA',
            'CORDOBA',
            'FILANDIA',
            'GENOVA',
            'LA TEBAIDA',
            'MONTENEGRO',
            'QUIMBAYA',
            'SALENTO',
            'APIA',
            'BALBOA',
            'BELEN DE UMBRIA',
            'BETULIA',
            'DOSQUEBRADAS',
            'GUATICA',
            'LA CELIA',
            'LA VIRGINIA',
            'MARSELLA',
            'MISTRATO',
            'PEREIRA',
            'PUEBLO RICO',
            'QUINCHIA',
            'SANTA ROSA DE CABAL',
            'SANTUARIO',
            'PROVIDENCIA',
            'SAN ANDRES',
            'AGUADA',
            'ALBANIA',
            'ARATOCA',
            'BARBOSA',
            'BARICHARA',
            'BARRANCABERMEJA',
            'BOLIVAR',
            'BUCARAMANGA',
            'CABRERA',
            'CALIFORNIA',
            'CAPITANEJO',
            'CARCASI',
            'CEPITA',
            'CERRITO',
            'CHARALA',
            'CHARTA',
            'CHIMA',
            'CHIPATA',
            'CIMITARRA',
            'CONCEPCION',
            'CONFINES',
            'CONTRATACION',
            'COROMOTO',
            'CURITI',
            'EL CARMEN',
            'EL CENTRO',
            'EL GUACAMAYO',
            'EL PENON',
            'EL PLAYON',
            'ENCINO',
            'ENCISO',
            'FLORIAN',
            'FLORIDABLANCA',
            'GALAN',
            'GAMBITA',
            'GIRON',
            'GUACA',
            'GUADALUPE',
            'GUAPOTA',
            'GUAVATA',
            'GUEPSA',
            'HATO',
            'JESUS MARIA',
            'JORDAN',
            'LA BELLEZA',
            'LA PAZ',
            'LANDAZURI',
            'LEBRIJA',
            'LOS SANTOS',
            'MACARAVITA',
            'MALAGA',
            'MATANZA',
            'MOGOTES',
            'MOLAGAVITA',
            'OCAMONTE',
            'OIBA',
            'ONZAGA',
            'PALMAR',
            'PALMAS DEL SOCORRRO',
            'PARAMO',
            'PIEDECUESTA',
            'PINCHOTE',
            'PUENTE NACIONAL',
            'PUERTO PARRA',
            'PUERTO WILCHES',
            'RIONEGRO',
            'SABANA DE TORRES',
            'SAN ANDRES',
            'SAN BENITO',
            'SAN FRANCISCO',
            'SAN GIL',
            'SAN JOAQUIN',
            'SAN JOSE DE S',
            'SAN JOSEMIRANDA',
            'SAN MIGUEL',
            'SAN VICENTE DE CHUCURY',
            'SANTA BARBARA',
            'SANTA HELENA DEL OPION',
            'SIMACOTA',
            'SOCORRO',
            'SUAITA',
            'SUCRE',
            'SURATA',
            'TONA',
            'VALLE SAN JOSE',
            'VELEZ',
            'VETAS',
            'VILLANUEVA',
            'ZAPATOCA',
            'BUENAVISTA',
            'CAIMITO',
            'CHALAN',
            'COLOSO',
            'COROZAL',
            'GALERAS',
            'GUARANDA',
            'LA UNION',
            'LOS PALMITOS',
            'MAJAGUAL',
            'MORROA',
            'OVEJAS',
            'PALMITO',
            'SAMPUES',
            'SAN BENITO ABAD',
            'SAN JUAN BETULIA',
            'SAN MARCOS',
            'SAN ONOFRE',
            'SAN PEDRO',
            'SINCE',
            'SINCELEJO',
            'SUCRE',
            'TOLU',
            'TOLUVIEJO',
            'ALPUJARRA',
            'ALVARADO',
            'AMBALEMA',
            'ANZOATEQUI',
            'ARMERO',
            'ATACO',
            'CADIZ',
            'CAJAMARCA',
            'CARMEN DE APICALA',
            'CASABLANCA',
            'CHAPARRAL',
            'CHICORAL',
            'COELLO',
            'COYAIMA',
            'CUNDAY',
            'DOLORES',
            'ESPINAL',
            'FALAN',
            'FLANDES',
            'FRESNO',
            'GAITANA',
            'GUAMO',
            'HERRERA',
            'HERVEO',
            'HONDA',
            'IBAGUE',
            'ICONONZO',
            'JUNIN',
            'LERIDA',
            'LIBANO',
            'MARIQUITA',
            'MELGAR',
            'MURILLO',
            'NATAGAIMA',
            'ORTEGA',
            'PALO CABILDO',
            'PIEDRAS',
            'PLANADAS',
            'PLAYARICA',
            'PRADO',
            'PURIFICACION',
            'RIOBLANCO',
            'RONCESVALLES',
            'ROVIRA',
            'SALDANA',
            'SAN ANTONIO',
            'SAN LUIS',
            'SANTA ISABEL',
            'SANTA TERESA',
            'SANTIAGO PEREZ',
            'SUAREZ',
            'TRES ESQUINAS',
            'VALLE DE SAN JUAN',
            'VENADILLO',
            'VILLAHERMOSA',
            'VILLARICA',
            'ALCALA',
            'ANDALUCIA',
            'ANSERMANUEVO',
            'ARGELIA',
            'BOLIVAR',
            'BUENAVENTURA',
            'BUGA',
            'BUGALAGRANDE',
            'CAICEDONIA',
            'CALI',
            'CANDELARIA',
            'CARTAGO',
            'DAGUA',
            'DARIEN',
            'EL AGUILA',
            'EL CAIRO',
            'EL CERRITO',
            'EL DOVIO',
            'FLORIDA',
            'GINEBRA',
            'GUACARI',
            'JAMUNDI',
            'LA CUMBRE',
            'LA UNION',
            'LA VICTORIA',
            'OBANDO',
            'PALMIRA',
            'PRADERA',
            'RESTREPO',
            'RIOFRIO',
            'ROLDANILLO',
            'SAN PEDRO',
            'SEVILLA',
            'TORO',
            'TRUJILLO',
            'TULUA',
            'ULLOA',
            'VERSALLES',
            'VIJES',
            'YOTOCO',
            'YUMBO',
            'ZARZAL',
            'CARURU',
            'MITU',
            'PACOA',
            'YAVARATE',
            'NUEVA ANTIOQUIA',
            'PRIMAVERA',
            'PUERTO CARRENO',
            'SAN JOSE OCUPE',];
        $products = json_decode($client->request('GET',
            $baseUrl . '?operation=describe&sessionName=' . $sessionName . '&elementType=Potentials')->getBody())->result->fields;
        $users = json_decode($client->request('GET',
            $baseUrl . '?operation=query&sessionName=' . $sessionName . '&query=select * from Users;')->getBody())->result;
        $medicines = json_decode($client->request('GET',
            $baseUrl . '?operation=query&sessionName=' . $sessionName . '&query=select * from Potentials;')->getBody())->result;
        $helps = json_decode($client->request('GET',
            $baseUrl . '?operation=describe&sessionName=' . $sessionName . '&elementType=HelpDesk')->getBody())->result->fields;
        return view('layouts.helpdesk', compact(['helps', 'users', 'medicines', 'cities', 'currentTime']));
    }

    function createhelp(RequestAlias $request){
        $baseUrl = 'https://server3.datacrm.la/datacrm/sanofi/webservice.php';
        $data = $request->all();

        $client = new Client(
            [
                'defaults' => [
                    'headers'  => [
                        'content-type' => 'application/x-www-form-urlencoded',
                        'Accept' => 'application/json'
                    ],
                ],
            ]
        );
        $sessionname = $this->getSessionName();
        try{
            $request = $client->request('POST', $baseUrl,  [
                'form_params' => [
                    'elementType'=> 'HelpDesk',
                    'operation' => 'create',
                    'element' => urlencode(json_encode($data)),
                    'sessionName'=> $sessionname
                ]
            ]);
            return redirect()->route('front');
        }catch (ExceptionAlias $e){

        }
    }

    private function getFieldsToShow($fields){
        $fieldsReturn = [];
        foreach ($fields as $field){
            foreach ($this->formFields as $formField){
                if($field->name == $formField['internalCode']){
                    $fieldsReturn[$formField['order']] = $field;
                }
            }
        }
        ksort($fieldsReturn);
        return $fieldsReturn;
    }
}
